index:
    path: /
    controller: App\Controller\GeneralController::indexAction

rechercher_bouteilles:
    path: /bouteilles
    controller: App\Controller\BouteilleController::rechercherBouteillesAction
    
supprimer_bouteille:
    path: /{idBouteille}/supprimer
    controller: App\Controller\BouteilleController::supprimerBouteilleAction
            
modifier_bouteille:
    path: /{idBouteille}/modifier
    controller: App\Controller\BouteilleController::modifierBouteilleAction
    
rechercher_membres:
    path: /membres
    controller: App\Controller\MembreController::rechercherMembresAction