index:
    path: /
    defaults: { _controller: 'App\Controller\GeneralController::indexAction' }

rechercher_bouteilles:
    path: /bouteilles
    defaults: { _controller: 'App\Controller\BouteilleController::rechercherBouteillesAction' }
    
supprimer_bouteille:
    path: /bouteille{idBouteille}/supprimer
    defaults: { _controller: 'App\Controller\BouteilleController::supprimerBouteilleAction' }
    
rechercher_membres:
    path: /membres
    defaults: { _controller: 'App\Controller\MembreController::rechercherMembresAction' }